### ISSUE TITLE
Constant constraints in gurobi solver.

### ISSUE THREAD

**Issue by phischu** [vagmcs/Optimus#15]
Hi, currently if we try to add a constant constraint while using the gurobi solver we get a pattern match failure.

The incomplete match is [here](https://github.com/vagmcs/Optimus/blob/9cc27a5871d4c94dca6d574a67fc24157c80b193/solver-gurobi/src/main/scala/optimus/optimization/Gurobi.scala#L203).

**Comment by vagmcs** [comment]
Hello @phischu,

Can you please add an example of the constraint you are trying to add (or the code that you are trying to run) in order to be able to fix it.

Thank you

**Comment by phischu** [comment]
Ok.

``` scala
package main

import optimus.algebra._
import optimus.optimization._

object Main extends App {

  implicit val problem = MIProblem(SolverLib.gurobi)

  val x = MPIntVar("x", 0 to 1)

  minimize(x*x)

  val y : Expression = 1

  subjectTo(y <= 1)

  start()

  println(x)

  release()

}
```

**Comment by vagmcs** [comment]
Hello @phischu

I pushed a fix and merged it into the master branch. It should be ok now.
