### ISSUE TITLE
Constant in cost function

### ISSUE THREAD

**Issue by rgugliel** [vagmcs/Optimus#21]
I noticed something that is a bit confusing.

Consider the following code:
```
import optimus.optimization._

object TestOptimus extends App {
  implicit val problem = LQProblem(SolverLib.ojalgo)

  val x = MPFloatVar("x", 0, 10)

  maximize(x + 1)
  add(x <:= 1)

  start()
  println("objective: " + objectiveValue)
  println("x = " + x.value)

  release()
}
```

The output is:
```
objective: 1.0 /// I was expecting two, here
x = Some(1.0)
```

I have questions:

- Is this reasonable that the constant term is forgotten ?
- If yes, would it be interesting to prevent user to use constant terms in cost function?

Thanks!

**Comment by vagmcs** [comment]
Hello @rgugliel,

I pushed a fix for this problem in the develop branch (see commit c0089a2). Now constant terms are supported in objective expressions.

**Comment by rgugliel** [comment]
Very nice, thanks!
