### ISSUE TITLE
Quadratic objective function + integer variable constraints?

### ISSUE THREAD

**Issue by yomna-stripe** [vagmcs/Optimus#22]
Hi @vagmcs,

First, thanks for all your work developing and maintaining this library. It's been great to use so far.

I'm having a problem where it's not clear how to define a quadratic objective function where the variables have integer constraints.

Here is a small example:
```
import optimus.algebra._
import optimus.optimization._

object QuadraticExperriment{
  def main(args: Array[String]): Unit = {
    implicit val problem = MIProblem(SolverLib.ojalgo)

    val x = MPIntVar("x", 0 to 1000)
    minimize(x*x - x + 0.25)
    start()
    release()
    println("x = " + x.value)
  }
}
```

The result from running this is:
```
Solution status is Optimal
x = Some(0.5)
```
... but `x` was specified as an `MPIntVar` (which should constrain it to be an integer?).

Alternatively, can the `MIProblem` type handle quadratic objective functions? We tried a small experiment, and it seemed to work, but for our larger code it seemed to run forever and not terminate.

**Comment by vagmcs** [comment]
Hello @yomna-stripe,

I will try to check your example next week.

Apart from that, MIProblem defines [integer linear programming](https://en.wikipedia.org/wiki/Integer_programming) problems which is known to be NP-complete in the general case. That means that there is no effective way of solving the problem fast (in polynomial time) and therefore it is logical to be slow for many variables and constraints. I think that this may be the reason that your larger code runs forever. Another problem may be that ojalgo is not so fast as proprietary solvers, have you tried gurobi?

**Comment by vagmcs** [comment]
Hello @yomna-stripe,

I ran your example but I am getting x = Some(0.0).

**Comment by yomna-stripe** [comment]
@vagmcs 

Hm, that's strange. Both a colleague and I ran it and we were getting `x = Some(0.5)`. Is there some way to capture logs about what's happening that we could include in this issue report?

**Comment by vagmcs** [comment]
@yomna-stripe 

I am not sure if there is a way to capture logs about this issue because one should log the internal solver, that is, ojalgo, which is used by Optimus. What version of Java and Scala are you using in your project? I ran your example using Java 1.8 and Scala 2.12.

**Comment by apete** [comment]
If you haven't already you should upgrade to the latest version:

https://github.com/optimatika/ojAlgo/wiki/v45

To get log output from ojAlgo you can set `model.options.progress(...)` or `model.options.debug(...)` and perhaps also set `model.options.logger_appender` to something that suits your needs.

A large MIP with quadratic objective function would be difficult for ojAlgo.

**Comment by vagmcs** [comment]
Thank you @apete. I will upgrade ojalgo for the next release. Are there any fixes regarding the integer solutions in version 45?

The change log of v45 states the following: 
"Fixed a whole bunch of problems, mainly related to rounding errors."

In that case I should make a hotfix for the master branch.

**Comment by apete** [comment]
Those were problems with the presolver functionality resulting in incorrect solution states (Infeasible rather than Optimal...) The solutions were typically correct, and the test cases we had would never call the actual solvers.

**Comment by yomna-stripe** [comment]
Hi @vagmcs. Both my colleague and I ran this using Java 1.8 and Scala 2.12, same as you.

**Comment by vagmcs** [comment]
Hello @yomna-stripe,

Do you still has this issue with Optimus version `3.0.0`?
