### ISSUE TITLE
Change in implicit behavior in 3.0.0 ?

### ISSUE THREAD

**Issue by rgugliel** [vagmcs/Optimus#23]
Hi,
I'm sorry to come with a very naive (and stupid?) question.

I'm trying to update to the version 3.0.0 in my project and it seems that the implicit does not work anymore:
```
implicit val model: MPModel    = MPModel(LPTimeFeasibility.solverLib)
val x = MPFloatVar("x", 100, 200)
add(x >:= 0)
model.add(x >:= 0)
```

The third line gives error from compilation.

Is this related to scala version ? Or...?

Thanks!

Rafael

P.S. I can run the whole test suite when cloning the repo.

**Comment by vagmcs** [comment]
Hello @rgugliel,

If you are running Scala 2.11 or 2.12 you should be fine. If you added Optimus as an sbt dependency  you would get an error for different Scala versions.

Apart from that, I tested your example and everything seems to work fine for me (I run Scala 2.12, but it should also work for 2.11. What version are you running?). Specifically I wrote the following code (try it if you like):

```scala
import optimus.optimization.enums.SolverLib
import optimus.optimization.model.MPFloatVar

object Test extends App {
  implicit val model: MPModel = MPModel(SolverLib.oJSolver)
  val x = MPFloatVar("x", 100, 200)
  add(x >:= 0)
  model.add(x >:= 0)
}
```
I used the oJSolver in my example. You are using the parameter`LPTimeFeasibility.solverLib` which, I suppose, is a pointer to some SolverLib enum in your project. What solver did you use exactly?

**Comment by rgugliel** [comment]
Hi @vagmcs ,
Thanks for your answer.

Here are some more info:

* It seems that I anyway need the import optimus.optimization.MPModel , even with the example that you gave or the one in the doc (https://github.com/vagmcs/Optimus/blob/master/docs/linear.md)

* If I take the LPSolveSpecTest, it seems that the implicit add works only when the "package optimus.optimization" is present ; is that normal?

Thanks.

Rafael

P.S. I usually use lp but result is the same with oj

**Comment by vagmcs** [comment]
Hello @rgugliel,

Yes, I ran the above example inside Optimus so it automatically finds the libraries. But if Optimus is a dependency you definitely need to import optimus.optimization because the implicit functions are inside the optimization package object. Maybe that is the reason why you get a compile error. But in any IDE I think it will automatically propose to you the import, because it performs indexing and finds the dependency. Now if you are using a simple text editor, such as sublime, you may need to declare it for yourself.

**Comment by rgugliel** [comment]
Ok, thanks.

Then I would suggest to update the imports of the minimal example there https://github.com/vagmcs/Optimus/blob/master/docs/linear.md to :

```
import optimus.optimization._
import optimus.optimization.enums.SolverLib
import optimus.optimization.model.MPFloatVar
```

So that it works out of the box. 

What do you think?

**Comment by vagmcs** [comment]
Yes you are right, it might confuses. Do you want to do it or shall I fix it?

PS. In case you want to fix it please make a pull request in the develop branch **not** in master.
