### ISSUE TITLE
Problem solving models sequentially (Gurobi bronze license)

### ISSUE THREAD

**Issue by pszczolisty** [vagmcs/Optimus#28]
I have Gurobi bronze license, which does not permit simultaneous usage (see http://www.gurobi.com/products/licensing-pricing/licensing-overview).

If I try to solve multiple models sequentially within context of the same `sbt run`:

1.  For the first model everything works fine, the Gurobi job runs and returns a result.
2. When the subsequent model is about to be solved, following error is thrown:
```
Thrown: gurobi.GRBException: Job queueing feature is disabled
gurobi.GRBEnv.<init>(GRBEnv.java:47)
gurobi.GRBEnv.<init>(GRBEnv.java:32)
optimus.optimization.Gurobi.<init>(Gurobi.scala:32)
sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.lang.reflect.Constructor.newInstance(Constructor.java:423)
java.lang.Class.newInstance(Class.java:442)
optimus.optimization.SolverFactory$.instantiate(SolverFactory.scala:40)
optimus.optimization.MPModel.solver$lzycompute(MPModel.scala:43)
optimus.optimization.MPModel.solver(MPModel.scala:43)
optimus.optimization.MPModel.start(MPModel.scala:124)
```

My workflow for each model is:

```
model = MPModel(...)

// setup the model

model.start(...)
model.release()
```

It feels like this might be caused by somehow incomplete cleanup after the first computation finishes. In fact, the log 

```
Compute Server job ID: 9672bbe6-fd51-4f42-9c91-d40b275c4d7e
Capacity available on 'ip-172-31-18-66' - connecting...
Established HTTPS encrypted connection
[INFO ]:
    _________                   ______ _____
    __  ____/___  _________________  /____(_)
    _  / __ _  / / /_  ___/  __ \_  __ \_  /
    / /_/ / / /_/ /_  /   / /_/ /  /_/ /  /
    \____/  \__._/ /_/    \____//_____//_/
```

appears only for the first model, and not the second.

Running two models after each other by separately calling `sbt run` does not exhibit the problem.

I'm using Optimus 3.1.0.

**Comment by vagmcs** [comment]
Hi @pszczolisty,

I think this might be a problem with the [Gurobi environment release call](https://github.com/vagmcs/Optimus/blob/8355a6307dbc042f77db39d4d185bc3c190e3ea7/solver-gurobi/src/main/scala/optimus/optimization/Gurobi.scala#L260) inside the release() method of the solver. Can you delete that line, publish locally Optimus and test if everything works correctly in your setup?

**Comment by pszczolisty** [comment]
That was a close guess, @vagmcs!
Deleting that line didn't help, but deleting the next one (`underlyingSolver.getEnv.dispose()`) did :)
Gurobi successfully ran two jobs in a row, each time logging something like this:

```
Compute Server job ID: 0c27e9dc-78f6-4187-830e-48eeabef900a
Capacity available on 'ip-172-31-28-222' - connecting...
Established HTTPS encrypted connection
[INFO ]:
    _________                   ______ _____
    __  ____/___  _________________  /____(_)
    _  / __ _  / / /_  ___/  __ \_  __ \_  /
    / /_/ / / /_/ /_  /   / /_/ /  /_/ /  /
    \____/  \__._/ /_/    \____//_____//_/
```

**Comment by vagmcs** [comment]
Thank you @pszczolisty, I will include this fix in the next release.
