### ISSUE TITLE
Warm start

### ISSUE THREAD

**Issue by iliyamarkov** [vagmcs/Optimus#30]
Hello,

Is there a way to warm start a MIP model with Optimus when using LPSolve?

Thank you very much
Best
Iliya

**Comment by vagmcs** [comment]
Hi @iliyamarkov,

Currently there is no such feature. I am not even sure if the underlying solvers support something like that. Have you ever tried it using one of the four solvers as standalone?

**Comment by iliyamarkov** [comment]
Hello,

Yes, this is something standard you can do in Gurobi and CPLEX through
their native APIs. It can be used for starting the solver with a solution
found by a heuristic so you can (hopefully) speed up the process.
I am not sure about the other two solvers, which I have not used through
their native APIs.

Is there any plans of including such functionality in Optimus in the future?

Thanks
Iliya

**Comment by vagmcs** [comment]
I had no plans for it, but it seems a useful feature. We can add this functionality in a future release. I can look into it when I got more time but I don't think it will be anytime soon. Of course, you can implement it yourself if you like and make a PR into the develop branch.

**Comment by iliyamarkov** [comment]
Thanks! I will look into it when I have some time.
