### ISSUE TITLE
No such method error while instantiating model

### ISSUE THREAD

**Issue by mmacha** [vagmcs/Optimus#31]
Installed the core package through maven, trying to replicate the Mixed Integer programming tutorial. I keep getting the following error when I do
> implicit val model = MPModel(SolverLib.oJSolver)
> java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V

The following imports work fine.  

> import optimus.optimization._
import optimus.optimization.enums.SolverLib
import optimus.optimization.model.MPFloatVar
import optimus.optimization.model.MPIntVar

I did try installing the oj, lp dependencies from maven but was not able to rectify the issue. Could you please help.

**Comment by vagmcs** [comment]
Hello @mmacha,

What version of Optimus, Scala and Java are you using? Everything works fine for me. Can you please attach the full code you are trying to run?

**Comment by mmacha** [comment]
Hi @vagmcs ,
          Thanks for responding. I am on Spark 2.4.0, Scala 2.1.1. I've attached the code snippet along with the error.

![image](https://user-images.githubusercontent.com/41309131/59529619-5f806780-8e96-11e9-9869-df9713b64998.png)

**Comment by vagmcs** [comment]
Hi @mmacha,

Can you please also tell me your Java and Optimus version? Moreover, it would be very helpful to run the same example on an IDE (IntelliJ, Eclipse, VSCode) and tell me if you get the same error. I suspect this may not be a problem with Optimus but the with the build process.
