### ISSUE TITLE
ojSolver: Time abort not working in case of feasible state

### ISSUE THREAD

**Issue by danoliv** [vagmcs/Optimus#35]
I found out that in case of long optimization the solver can ignore the time_abort set here 

https://github.com/vagmcs/Optimus/blob/641052e425ef1dde134bc4e8611335b49ad79223/solver-oj/src/main/scala/optimus/optimization/oJSolver.scala#L246

this is mainly due to this 

https://github.com/optimatika/ojAlgo/blob/9b604f2639280fd42a31a89f6c895059c7d22447/src/org/ojalgo/optimisation/GenericSolver.java#L335

if the underling solver is in feasible state the optimization will continue.
As Optimus provides only time_abort the solver do not stop. 
A solution we are using is to set both the time_abort and time_suffice properties.
Example of the proposed solution :

https://github.com/danoliv/Optimus/blob/31c3c77312c75393bed7acf919f7330bc2822fb0/solver-oj/src/main/scala/optimus/optimization/oJSolver.scala#L247

**Comment by apete** [comment]
That seems like a problem with ojAlgo: https://github.com/optimatika/ojAlgo/pull/259/files

**Comment by danoliv** [comment]
Thanks @apete, looking at the code it looked like an intentional behavior so I hesitate to open the issue there. Also I wanted to fix it with the version of ojAlgo that we are currently using.

**Comment by apete** [comment]
It makes sense to always set `time_suffice`, either to the same as `time_abort` or something smaller. That's what I normally do - and probably why that logic glitch was not discovered before.

**Comment by vagmcs** [comment]
Issue solved (see merge request #36)
