### ISSUE TITLE
Value positive is not a member of object optimus.optimization.model.MPFloatVar

### ISSUE THREAD

**Issue by arcteixeira** [vagmcs/Optimus#38]
Hi,

I'm running the code from the example:

`
import optimus.optimization._
import optimus.optimization.enums.SolverLib
import optimus.optimization.model.MPFloatVar

implicit val model: MPModel = MPModel(SolverLib.oJSolver)

// Both variables are positive, that is, bounds are in [0, +inf]
val x = MPFloatVar.positive("x")
val y = MPFloatVar.positive("y")

minimize(-8*x - 16*y + x*x + 4*y)
subjectTo(
  x + y <:= 5,
  x <:= 3
)

start()

println(s"objective: $objectiveValue")
println(s"x = ${x.value} y = ${y.value}")

release()
`

My Scala version is 2.11.12, so according to the Version Matrix I added the following dependencies:

`"com.github.vagmcs" %% "optimus" % "3.2.4",
  "com.github.vagmcs" %% "optimus-solver-oj" % "3.2.4",
   "com.github.vagmcs" %% "optimus-solver-lp" % "3.2.4"`

But I keep getting the error "value positive is not a member of object optimus.optimization.model.MPFloatVar
val y = MPFloatVar.positive("y")". Weirdly enough it only happens for the second variable, if I use inly x there is no problem.

Can you please assist? Thanks in advance!

**Comment by vagmcs** [comment]
Hello @arcteixeira,

First, let me point out that this code is not correct since you have missed the multiplication operators in the `minimize(-8x - 16y + xx + 4y)` statement. You should write `minimize(-8*x - 16*y + x*x + 4*y)`. Apart from that, in my case the program runs just fine.

**Comment by arcteixeira** [comment]
Sorry, I cannot copy it correctly!

![image](https://user-images.githubusercontent.com/25318716/115243522-4e07e680-a123-11eb-8686-316ac49a6af6.png)
 This is the code that I'm trying to run.

**Comment by vagmcs** [comment]
I noticed that your example is written in a .sc file which is an ammonite script. I am not sure if everything run as expected. Can you please create a proper main class in Scala and run the same example?

```scala
import optimus.optimization._
import optimus.optimization.enums.SolverLib
import optimus.optimization.model.MPFloatVar

object Test extends App {

  implicit val model: MPModel = MPModel(SolverLib.oJSolver)

  // Both variables are positive, that is, bounds are in [0, +inf]
  val x = MPFloatVar.positive("x")
  val y = MPFloatVar.positive("y")

  minimize(-8*x - 16*y + x*x + 4*y)
  subjectTo(
    x + y <:= 5,
    x <:= 3
  )

  start()

  println(s"objective: $objectiveValue")
  println(s"x = ${x.value} y = ${y.value}")

  release()
}
```

**Comment by arcteixeira** [comment]
You're right, it works fine with a main class. I just assumed that if the `val x` creation worked ok, there was no reason why `val y` would fail. 

Thanks for such prompt reply.
