### ISSUE TITLE
CPLEX and Mosek

### ISSUE THREAD

**Issue by apete** [vagmcs/Optimus#6]
Hi,

ojAlgo has integrations to CPLEX and Mosek. Since you're already able to use the pure Java ojAlgo there is essentially no additional effort to use CPLEX or Mosek.

https://github.com/optimatika/ojSolverCPLEX
https://github.com/optimatika/ojSolverMosek

There's also a Gurobi integration, but it's not finished and I suppose not of interest to you since you already have that.

https://github.com/optimatika/ojSolverGurobi

Anders

**Comment by vagmcs** [comment]
Hi Anders,

Thanks for the update. I will consider your proposal.
