### ISSUE TITLE
Returning 0.999999 instead of 1 with binary variables

### ISSUE THREAD

**Issue by da-steve101** [vagmcs/Optimus#7]
I am running an ILP using gurobi. All the variables are binary ( created using MPIntVar( "...", 0 to 1 ) )
The values are returned as doubles and occasionally I see 0.999999 instead of 1 for variable.value.get
Just minor irritation as I was reading the result using == 1
Perhaps rounding the value for ILP to the nearest possible value is the way to go?

**Comment by vagmcs** [comment]
Yes, there should be a rounding to the nearest integer value in such cases. I will create a patch to solve the issue, probably next week.

**Comment by vagmcs** [comment]
Is it possible to provide an example program that this issue appears in order to be able to test the changes that I made into the code?

**Comment by da-steve101** [comment]
If u clone this: https://github.com/da-steve101/chisel-utils
checkout branch optimusTest and run sbt "testOnly *SumSchedulerSuite"
To verify your change look at the following locations:
https://github.com/da-steve101/chisel-utils/blob/optimusTest/src/main/scala/chiselutils/math/SumScheduler.scala#L517
https://github.com/da-steve101/chisel-utils/blob/optimusTest/src/main/scala/chiselutils/math/SumScheduler.scala#L528
https://github.com/da-steve101/chisel-utils/blob/optimusTest/src/main/scala/chiselutils/math/SumScheduler.scala#L538
https://github.com/da-steve101/chisel-utils/blob/optimusTest/src/main/scala/chiselutils/math/SumScheduler.scala#L540

Sorry the codes a bit crappy btw. Was just seeing if I could use ILP for something ( turns out I can't )

**Comment by vagmcs** [comment]
The examples on this issue are outdated since Optimus has been undergone major changes and updates in version 3.0.0. If you still has this problem please send me an example using the newer version.

Thank you.
