### ISSUE TITLE
installation instructions: `sbt dist` not a valid command

### ISSUE THREAD

**Issue by dportabella** [vagmcs/Optimus#8]
https://github.com/vagmcs/Optimus/blob/master/docs/building_and_linking.md

$ git clone https://github.com/vagmcs/Optimus.git
$ cd Optimus
$ sbt dist
[error] Not a valid command: dist (similar: set, iflast, last)

**Comment by anskarl** [comment]
It seems that the sbt-native-packager plugin and its configuration are missing from sbt. I am preparing a fix.

**Comment by vagmcs** [comment]
Fixed by @anskarl. It should be ok now.

**Comment by anskarl** [comment]
@dportabella Please note that the fix is also applied on master branch (stable version of API that is used in other projects, e.g., LoMRF)

**Comment by dportabella** [comment]
Thx!
